
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int STRING_LITERAL = 21;
  public static final int MINUS_OPERATOR = 25;
  public static final int TRUE_KEYWORD = 16;
  public static final int LESS_THAN_OPERATOR = 29;
  public static final int RIGHT_BRACKET = 42;
  public static final int PRINT_KEYWORD = 13;
  public static final int LESS_THAN_OR_EQUAL_OPERATOR = 31;
  public static final int RIGHT_SQUARE_BRACKET = 44;
  public static final int DIVISION_OPERATOR = 28;
  public static final int BOOLEAN_KEYWORD = 6;
  public static final int CHARACTER_KEYWORD = 5;
  public static final int COMMA_DELIMITER = 38;
  public static final int SEMICOLON_DELIMITER = 37;
  public static final int QUESTION_MARK_OPERATOR = 46;
  public static final int COLON_DELIMITER = 45;
  public static final int FINAL_KEYWORD = 3;
  public static final int CHARACTER_LITERAL = 20;
  public static final int RIGHT_PARENTHESIS = 40;
  public static final int MULTIPLICATION_OPERATOR = 27;
  public static final int EOF = 0;
  public static final int GREATER_THAN_OR_EQUAL_OPERATOR = 32;
  public static final int LEFT_SQUARE_BRACKET = 43;
  public static final int AND_OPERATOR = 36;
  public static final int error = 1;
  public static final int EQUALS_OPERATOR = 23;
  public static final int NOT_EQUAL_OPERATOR = 34;
  public static final int PRINTLINE_KEYWORD = 14;
  public static final int FLOATING_POINT_LITERAL = 22;
  public static final int PLUS_OPERATOR = 24;
  public static final int TILDE_OPERATOR = 26;
  public static final int EQUALITY_OPERATOR = 33;
  public static final int READ_KEYWORD = 12;
  public static final int FLOAT_KEYWORD = 7;
  public static final int RETURN_KEYWORD = 15;
  public static final int WHILE_KEYWORD = 11;
  public static final int GREATER_THAN_OPERATOR = 30;
  public static final int INTEGER_KEYWORD = 4;
  public static final int CLASS_KEYWORD = 2;
  public static final int OR_OPERATOR = 35;
  public static final int FALSE_KEYWORD = 17;
  public static final int VOID_KEYWORD = 8;
  public static final int IF_KEYWORD = 9;
  public static final int ELSE_KEYWORD = 10;
  public static final int LEFT_BRACKET = 41;
  public static final int LEFT_PARENTHESIS = 39;
  public static final int INTEGER_LITERAL = 19;
  public static final int IDENTIFIER = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS_KEYWORD",
  "FINAL_KEYWORD",
  "INTEGER_KEYWORD",
  "CHARACTER_KEYWORD",
  "BOOLEAN_KEYWORD",
  "FLOAT_KEYWORD",
  "VOID_KEYWORD",
  "IF_KEYWORD",
  "ELSE_KEYWORD",
  "WHILE_KEYWORD",
  "READ_KEYWORD",
  "PRINT_KEYWORD",
  "PRINTLINE_KEYWORD",
  "RETURN_KEYWORD",
  "TRUE_KEYWORD",
  "FALSE_KEYWORD",
  "IDENTIFIER",
  "INTEGER_LITERAL",
  "CHARACTER_LITERAL",
  "STRING_LITERAL",
  "FLOATING_POINT_LITERAL",
  "EQUALS_OPERATOR",
  "PLUS_OPERATOR",
  "MINUS_OPERATOR",
  "TILDE_OPERATOR",
  "MULTIPLICATION_OPERATOR",
  "DIVISION_OPERATOR",
  "LESS_THAN_OPERATOR",
  "GREATER_THAN_OPERATOR",
  "LESS_THAN_OR_EQUAL_OPERATOR",
  "GREATER_THAN_OR_EQUAL_OPERATOR",
  "EQUALITY_OPERATOR",
  "NOT_EQUAL_OPERATOR",
  "OR_OPERATOR",
  "AND_OPERATOR",
  "SEMICOLON_DELIMITER",
  "COMMA_DELIMITER",
  "LEFT_PARENTHESIS",
  "RIGHT_PARENTHESIS",
  "LEFT_BRACKET",
  "RIGHT_BRACKET",
  "LEFT_SQUARE_BRACKET",
  "RIGHT_SQUARE_BRACKET",
  "COLON_DELIMITER",
  "QUESTION_MARK_OPERATOR"
  };
}

